// packages/solid/src/components/input/input.tsx
import { styled } from '@hanekokoro-ui/styled-system/jsx';
import { input, type InputVariantProps } from '@hanekokoro-ui/styled-system/recipes';
import type { Assign, ElementType, HTMLStyledProps } from '@hanekokoro-ui/styled-system/types';
import type { PolymorphicProps } from '@kobalte/core';

export type InputProps<T extends ElementType = 'input'> = PolymorphicProps<
  T,
  Assign<HTMLStyledProps<T>, InputVariantProps>
>;

const Root = styled('input', input);

// Workaround that directly specify type in the const export above
// makes TypeScript too slow to emit types
export function Input<T extends ElementType = 'input'>(props: InputProps<T>) {
  // @ts-ignore
  return <Root {...props} />;
}

// src/components/input/input.tsx
import { ark, type Assign, type HTMLArkProps } from '@ark-ui/solid';
import type { ComponentProps } from 'solid-js';
import { styled, type StyledComponent } from '@shadowrz/hanekokoro-ui/styled-system/jsx';
import { input, type InputVariantProps } from '@shadowrz/hanekokoro-ui/styled-system/recipes';

export type InputProps = ComponentProps<typeof Input>;
export const Input = styled(ark.input, input) as StyledComponent<
  'input',
  Assign<HTMLArkProps<'input'>, InputVariantProps>
>;
