// src/components/ui/styled/text.tsx
import type { ComponentProps } from 'solid-js';
import { styled } from '@hanekokoro-ui/styled-system/jsx';
import { type TextVariantProps, text } from '@hanekokoro-ui/styled-system/recipes';
import type { StyledComponent } from '@hanekokoro-ui/styled-system/types';

type ParagraphProps = TextVariantProps & { as?: JSX.ElementType };

export type TextProps = ComponentProps<typeof Text>;
export const Text = styled('p', text) as StyledComponent<'p', ParagraphProps>;

// packages/solid/src/components/text/text.tsx
import { styled, type HTMLStyledProps } from '@hanekokoro-ui/styled-system/jsx';
import { text, type TextVariantProps } from '@hanekokoro-ui/styled-system/recipes';
import type { Assign, ElementType } from '@hanekokoro-ui/styled-system/types';
import type { PolymorphicProps } from '@kobalte/core';

export type TextProps<T extends ElementType = 'p'> = PolymorphicProps<T, Assign<HTMLStyledProps<T>, TextVariantProps>>;
const Unwrapped = styled('p', text);

// Workaround that directly specify type in the const export above
// makes TypeScript too slow to emit types
export function Text<T extends ElementType = 'p'>(props: TextProps<T>) {
  // @ts-ignore
  return <Unwrapped {...props} />;
}
