// src/components/textarea/textarea.tsx
import { ark, type Assign, type HTMLArkProps } from '@ark-ui/solid';
import type { ComponentProps } from 'solid-js';
import { styled, type StyledComponent } from '@shadowrz/hanekokoro-ui/styled-system/jsx';
import { textarea, type TextareaVariantProps } from '@shadowrz/hanekokoro-ui/styled-system/recipes';

export type TextareaProps = ComponentProps<typeof Textarea>;
export const Textarea = styled(ark.textarea, textarea) as StyledComponent<
  'textarea',
  Assign<HTMLArkProps<'textarea'>, TextareaVariantProps>
>;

// packages/solid/src/components/textarea/textarea.tsx
import { styled, type HTMLStyledProps } from '@hanekokoro-ui/styled-system/jsx';
import { textarea, type TextareaVariantProps } from '@hanekokoro-ui/styled-system/recipes';
import type { Assign, ElementType } from '@hanekokoro-ui/styled-system/types';
import type { PolymorphicProps } from '@kobalte/core';

export type TextareaProps<T extends ElementType = 'textarea'> = PolymorphicProps<
  T,
  Assign<HTMLStyledProps<T>, TextareaVariantProps>
>;
const Unwrapped = styled('textarea', textarea);

// Workaround that directly specify type in the const export above
// makes TypeScript too slow to emit types
export function Textarea<T extends ElementType = 'textarea'>(props: TextareaProps<T>) {
  // @ts-expect-error: Hack.
  return <Unwrapped {...props} />;
}
